CREATE TABLE If NOT EXISTS todo_chat.user (
  id BIGINT UNSIGNED AUTO_INCREMENT COMMENT 'id',
  name VARCHAR(50) NOT NULL UNIQUE COMMENT 'ユーザー名',
  display_name VARCHAR(50) NOT NULL COMMENT '表示名',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '作成日時',
  created_by BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '作成者',
  version BIGINT UNSIGNED NOT NULL DEFAULT 1 COMMENT 'バージョン',
  PRIMARY KEY (id)
);
