app:
  version: @app.version@

spring:
  application:
    name: todo-chat

  datasource:
    url: jdbc:mysql://localhost:3306/
    username:
    password:

mybatis:
  mapper-locations: classpath*:/db/mapper/*.xml

openai:
  endpoint: # https://api.openai.com/v1/models/
  apikey:
  model: # gpt-4