# .github/workflows/ci.yml
name: CI

on:
  push:
    branches:
      - master
      - feature/semantic-kernel
      - feature/lang-chain4j
  pull_request:
    branches:
      - master
      - feature/semantic-kernel
      - feature/lang-chain4j

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set environment variables
        run: |
          echo "MYSQL_ROOT_PASSWORD=password" >> $GITHUB_ENV
          echo "MYSQL_DATABASE=todo_chat" >> $GITHUB_ENV
          echo "MYSQL_USER=todo_chat" >> $GITHUB_ENV
          echo "MYSQL_PASSWORD=password" >> $GITHUB_ENV
          echo "TZ=Asia/Tokyo" >> $GITHUB_ENV
          echo "APP_VERSION=${{ github.event.repository.default_branch }}" >> $GITHUB_ENV
          echo "OPENAI_ENDPOINT=endpoint" >> $GITHUB_ENV
          echo "OPENAI_APIKEY=apikey" >> $GITHUB_ENV
          echo "OPENAI_MODEL=model" >> $GITHUB_ENV
          echo "DOCUMENT_PATH=${{ github.workspace }}/documents" >> $GITHUB_ENV

      - name: Set up Docker Compose
        run: docker-compose up -d

      - name: Wait for MySQL to be healthy
        run: |
          for i in {1..30}; do
            if [ "$(docker inspect --format='{{.State.Health.Status}}' todo-chat-test)" == "healthy" ]; then
              echo "MySQL is healthy"
              exit 0
            fi
            sleep 2
          done
          echo "MySQL failed to become healthy"
          docker logs todo-chat-test
          exit 1
        working-directory: .

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/webapp/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Set application environment variables
        run: |
          echo "SPRING_DATASOURCE_URL=jdbc:mysql://localhost:3307/todo_chat" >> $GITHUB_ENV
          echo "SPRING_DATASOURCE_USERNAME=todo_chat" >> $GITHUB_ENV
          echo "SPRING_DATASOURCE_PASSWORD=password" >> $GITHUB_ENV
          echo "MYBATIS_MAPPER_LOCATIONS=classpath*:/db/mapper/*.xml" >> $GITHUB_ENV
          echo "OPENAI_ENDPOINT=endpoint" >> $GITHUB_ENV
          echo "OPENAI_APIKEY=apikey" >> $GITHUB_ENV
          echo "OPENAI_MODEL=model" >> $GITHUB_ENV

      - name: Build with Maven
        run: mvn -B package --file pom.xml -Dapp.version=${{ env.APP_VERSION }}
        working-directory: ./webapp

      - name: Run tests with Maven
        run: mvn test -Dapp.version=${{ env.APP_VERSION }}
        working-directory: ./webapp
